### ISSUE TITLE
loopd errors out on start

### ISSUE THREAD

**Issue by rationalflaneur** [lightninglabs/loop#33]
I get this error when I try to start `loopd`:

```
2019-03-25 20:09:08.772 [INF] LOOPD: Version: 0.1.0-alpha commit=
2019-03-25 20:09:08.772 [INF] LNDCLIENT: Creating lnd connection to localhost:10009
2019-03-25 20:09:08.773 [INF] LNDCLIENT: Connected to lnd
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/lightninglabs/loop/lndclient.(*lightningClient).GetInfo(0x1033920, 0x8f7000, 0x10280a0, 0x0, 0x0, 0x0)
	/home/admin/gocode/src/github.com/lightninglabs/loop/lndclient/lightning_client.go:143 +0x28c
github.com/lightninglabs/loop/lndclient.NewLndServices(0x7042fc, 0xf, 0x6fbc46, 0x6, 0x6fd2e0, 0x7, 0x0, 0x0, 0x0, 0x0, ...)
	/home/admin/gocode/src/github.com/lightninglabs/loop/lndclient/lnd_services.go:63 +0x244
main.getLnd(0x6fd2e0, 0x7, 0xdab1f8, 0x12384, 0xdc9248, 0x0)
	/home/admin/gocode/src/github.com/lightninglabs/loop/cmd/loopd/utils.go:13 +0x68
main.daemon(0x10948d0, 0x0, 0x0)
	/home/admin/gocode/src/github.com/lightninglabs/loop/cmd/loopd/daemon.go:23 +0x58
main.start(0x102e0b0, 0x0)
	/home/admin/gocode/src/github.com/lightninglabs/loop/cmd/loopd/main.go:89 +0x42c
main.main()
	/home/admin/gocode/src/github.com/lightninglabs/loop/cmd/loopd/main.go:32 +0x14
```

This is my lnd.conf:

```
[Application Options]
debuglevel=info
maxpendingchannels=5
alias=<alias>
color=#C74124
externalip=<external ip>
tlsextraip=<external ip>
rpclisten=0.0.0.0:10009

[Bitcoin]
bitcoin.active=1

# enable either testnet or mainnet
bitcoin.mainnet=1

bitcoin.node=bitcoind

[autopilot]
autopilot.active=0
autopilot.maxchannels=5
autopilot.allocation=0.6
```

**Comment by Roasbeef** [comment]
Is this built from master, or using the latest release?

**Comment by rationalflaneur** [comment]
Both `lnd` and `loop` should be built from master, unless I've messed something up. This is what I see when I do `lnd --version`:

```
lnd version 0.5.2-99-beta commit=queue/v1.0.1-136-g6ad8be25e1aaf4700bd86303ae534cf36c6199bf
```

**Comment by Roasbeef** [comment]
Hmm, unable to reproduce as is on master.

**Comment by rationalflaneur** [comment]
This is on a Thundroid OC2, BTW, not sure if any of the loopd installation instructions need to be different for it?

**Comment by joostjager** [comment]
Looks like it is tripping over the breaking change that was done some time ago to the `getinfo` call. Can you run a `lncli getinfo` and paste the output here?

**Comment by rationalflaneur** [comment]
Sure, here's the output:

```
{
	"version": "0.5.2-beta commit=v0.5.2-beta",
	"identity_pubkey": "<key>",
	"alias": "<alias>",
	"num_pending_channels": 0,
	"num_active_channels": 3,
	"num_inactive_channels": 1,
	"num_peers": 7,
	"block_height": 568893,
	"block_hash": "00000000000000000003d713c2d6664e6777691e9adbb9e42076db500896ee18",
	"best_header_timestamp": 1553607520,
	"synced_to_chain": true,
	"testnet": false,
	"chains": [],
	"uris": [
		"<key@ip>:9735"
	]
}

```

**Comment by rationalflaneur** [comment]
Is the version supposed to be different from when I run `lncli --version`? This is what I get when I do `lncli --version`:

`lncli version 0.5.2-99-beta commit=queue/v1.0.1-136-g6ad8be25e1aaf4700bd86303ae534cf36c6199bf`

**Comment by joostjager** [comment]
Ok, the cause of the crash is that the `chains` field is an empty list. Now the question is why it is empty.

**Comment by rationalflaneur** [comment]
Anything I can do to help diagnose why `chains` is empty?

**Comment by joostjager** [comment]
I could have a look at the lnd startup log. Can you drop that in pastebin?

**Comment by rationalflaneur** [comment]
@joostjager @Roasbeef solved! Seems like I just needed to restart `lnd` 🙈

I think this is what was missing (from startup logs):

```
Mar 26 12:16:37 asgardroid lnd[26759]: 2019-03-26 12:16:37.500 [INF] CHDB: Checking for schema update: latest_version=8, db_version=7
Mar 26 12:16:37 asgardroid lnd[26759]: 2019-03-26 12:16:37.500 [INF] CHDB: Performing database schema migration
Mar 26 12:16:37 asgardroid lnd[26759]: 2019-03-26 12:16:37.500 [INF] CHDB: Applying migration #8
Mar 26 12:16:37 asgardroid lnd[26759]: 2019-03-26 12:16:37.500 [INF] CHDB: Migrating to the gossip message store new key format
Mar 26 12:16:37 asgardroid lnd[26759]: 2019-03-26 12:16:37.500 [INF] CHDB: Migration to the gossip message store new key format 
```

**Comment by joostjager** [comment]
Hmm, I don't understand why it applied a migration after you already ran the latest master before.

**Comment by rationalflaneur** [comment]
Yeah, not sure what's up with that either. I had `lnd` running as a service, maybe `lncli stop` didn't stop that service, and I needed to shut down the service with `systemctl stop lnd`?

**Comment by joostjager** [comment]
I don't know how you configured it, but it sounds like you were just running an older version.

**Comment by tinova** [comment]
FWIW, it's happening for me too, but chains is not empty.

```
{
 "identity_pubkey": "<key>",
  "alias": "<alias>",
  "num_pending_channels": 0,
  "num_active_channels": 1,
  "num_peers": 2,
  "block_height": 569006,
  "block_hash": "0000000000000000001c22ca10017f3a763d6eaace2250bf7b40fb95817554f2",
  "synced_to_chain": true,
  "testnet": false,
  "chains": [
    "bitcoin"
  ],
  "uris": [
    "<key@ip>:9735"
  ],
  "best_header_timestamp": "1553679744",
  "version": "0.5.2-beta commit=v0.5.2-beta",
  "num_inactive_channels": 0
}
```

The error i get:

```
2019-03-27 09:58:51.897 [INF] LOOPD: Version: 0.1.0-alpha commit=
2019-03-27 09:58:51.897 [INF] LNDCLIENT: Creating lnd connection to localhost:10009
2019-03-27 09:58:51.899 [INF] LNDCLIENT: Connected to lnd
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/lightninglabs/loop/lndclient.(*lightningClient).GetInfo(0x19388a0, 0x8f6fe8, 0x182c080, 0x0, 0x0, 0x0)
        /home/pi/dev/loop/lndclient/lightning_client.go:143 +0x28c
github.com/lightninglabs/loop/lndclient.NewLndServices(0x7042ec, 0xf, 0x6fbc36, 0x6, 0x6fd2d0, 0x7, 0x0, 0x0, 0x0, 0x0, ...)
        /home/pi/dev/loop/lndclient/lnd_services.go:63 +0x244
main.getLnd(0x6fd2d0, 0x7, 0xdab1e8, 0x128c8, 0xdc92f8, 0x0)
        /home/pi/dev/loop/cmd/loopd/utils.go:13 +0x68
main.daemon(0x18848d0, 0x0, 0x0)
        /home/pi/dev/loop/cmd/loopd/daemon.go:23 +0x58
main.start(0x182a270, 0x0)
        /home/pi/dev/loop/cmd/loopd/main.go:89 +0x42c
main.main()
        /home/pi/dev/loop/cmd/loopd/main.go:32 +0x14
```

Let me know if you need more info

**Comment by joostjager** [comment]
The format of chains has changed. Your output indicates you are not running a new enough revision of `lnd`.

**Comment by tinova** [comment]
You are right, my fault entirely. Sorry for the noise.
