### ISSUE TITLE
Unable to run regtest loopserver docker image on Mac

### ISSUE THREAD

**Issue by joemphilips** [lightninglabs/loop#463]
**Expected behavior**

Run docker-compose on Mac under `regtest` and check loopserver is working fine

**Actual behavior**

loopserver throws segmentation violation error.
here's its output from `./regtest.sh start`
```
Recreating regtest_bitcoind_1 ... done
Recreating regtest_lndclient_1 ... done
Recreating regtest_lndserver_1  ... done
Recreating regtest_loopclient_1 ... done
Recreating regtest_loopserver_1 ... done
Waiting for nodes to start
Error response from daemon: Container 999597ce86eb927f29e9a14e41e1510ea16b75c139ce3ad9292aecd8c8562e7e is restarting, wait until the container is running
Error response from daemon: Container 999597ce86eb927f29e9a14e41e1510ea16b75c139ce3ad9292aecd8c8562e7e is restarting, wait until the container is running
```

and docker-compose logs

```
loopserver_1  | goroutine 1 [running]:
loopserver_1  | github.com/lightningnetwork/lnd.SetSubLogger(0xc000369700, 0x1992e17, 0x4, 0x1d1d538, 0xc00000f158, 0xc0005f9b38, 0x1, 0x1)
loopserver_1  | 	github.com/lightningnetwork/lnd@v0.13.0-beta.rc3/log.go:186 +0x85
loopserver_1  | main.SetupLoggers(0xc000369700, 0xc0004cf1a0, 0xc00054e360, 0xc00054e3c0, 0xc00054e420)
loopserver_1  | 	github.com/lightninglabs/nautilus/cmd/nautserver/log_regtest.go:35 +0x15d
loopserver_1  | main.start(0x200000003, 0xc000000180)
loopserver_1  | 	github.com/lightninglabs/nautilus/cmd/nautserver/main.go:303 +0x3d5
loopserver_1  | main.main()
loopserver_1  | 	github.com/lightninglabs/nautilus/cmd/nautserver/main.go:31 +0x26
loopserver_1  | 2022/02/19 12:34:11 WARNING: proto: file "rpc.proto" is already registered
loopserver_1  | A future release will panic on registration conflicts. See:
loopserver_1  | https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict
loopserver_1  | 
loopserver_1  | panic: runtime error: invalid memory address or nil pointer dereference
loopserver_1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15700e5]
loopserver_1  | 
```
**To reproduce**

on Mac
`git clone https://github.com/lightninglabs/loop && cd loop/regtest && ./regtest.sh start`

**System information**

`git rev-parse HEAD` returns `40882b74e434e1c2eda12d05488f4f80b03dfc29`

OS version: macOS Big Sur : v11.6.4

note: I can successfully run regtest docker-compose on my ubuntu machine.

** Why this matters**

I want to develop my own project which depends on loopserver, but I am forced to use linux machine to do so. What matters more is that others wishes to test my project are forced too.
I suppose the whole point of publishing docker image for loopserver is to enable running it in arbitrary environment, so this must be bug on loopserver?

**Comment by joemphilips** [comment]
woops nevermind,  it was because docker was caching the older version of loopserver, after specifying specific tag from dockerhub [v0.9.32-beta](https://hub.docker.com/layers/lightninglabs/loopserver/v0.9.32-beta/images/sha256-5a806e7ea160ffbdbf0a09f096a067d8c9bee551abd7ef28f26109e96ce8eed1?context=explore), it seems working fine.
